### ISSUE TITLE
MemoryError  when dataload

### ISSUE THREAD

**Issue by kieven2008** [ElectronicElephant/tiny_yolov3#3]
There are still some problem, Maybe the reason is that I run it in the Windows10, not linux OS?
I use mxnet-cu101mkl 1.6.0.
Could you be kind enough to give some advice,Thanks!

python.exe train.py
model loaded
loading annotations into memory...
Done (t=17.45s)
creating index...
index created!
dataset loaded
Traceback (most recent call last):
File "", line 1, in
File "D:\ProgramData\Anaconda3\envs\tinyyolo\lib\multiprocessing\spawn.py", line 105, in spawn_main
exitcode = _main(fd)
File "D:\ProgramData\Anaconda3\envs\tinyyolo\lib\multiprocessing\spawn.py", line 115, in _main
self = reduction.pickle.load(from_parent)
MemoryError
Traceback (most recent call last):
File "D:/work/2021/tiny_yolov3-master/train.py", line 277, in
async_net, train_dataset, args.data_shape, args.batch_size, args.num_workers, args)
File "D:/work/2021/tiny_yolov3-master/train.py", line 116, in get_dataloader
shuffle=True, batchify_fn=batchify_fn, num_workers=num_workers)
File "d:\work\2021\tiny_yolov3-master\gluon-cv\gluoncv\data\dataloader.py", line 261, in init
self._num_workers, initializer=_worker_initializer, initargs=[self._dataset])
File "D:\ProgramData\Anaconda3\envs\tinyyolo\lib\multiprocessing\context.py", line 119, in Pool
context=self.get_context())
File "D:\ProgramData\Anaconda3\envs\tinyyolo\lib\multiprocessing\pool.py", line 176, in init
self._repopulate_pool()
File "D:\ProgramData\Anaconda3\envs\tinyyolo\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
w.start()
File "D:\ProgramData\Anaconda3\envs\tinyyolo\lib\multiprocessing\process.py", line 112, in start
self._popen = self._Popen(self)
File "D:\ProgramData\Anaconda3\envs\tinyyolo\lib\multiprocessing\context.py", line 322, in _Popen
return Popen(process_obj)
File "D:\ProgramData\Anaconda3\envs\tinyyolo\lib\multiprocessing\popen_spawn_win32.py", line 89, in init
reduction.dump(process_obj, to_child)
File "D:\ProgramData\Anaconda3\envs\tinyyolo\lib\multiprocessing\reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe

**Comment by kieven2008** [comment]
python version
